build:
  image: gradle:6.5.1-jdk11
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx256m"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  stage: build
  script: gradle -i --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  image: gradle:6.5.1-jdk11
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx256m"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  stage: test
  script: gradle -i check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    name: "Tests report for $CI_JOB_NAME"
    when: always
    paths:
      - build/reports/tests
    reports:
      junit:  build/test-results/tests/TEST-*.xml
    expire_in: 1 week
