# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: gradle:6.5.1-jdk11

    steps:
    - uses: actions/checkout@v2

    - name: Assemble
      run: gradle -i assemble
  
  fastTest:
    runs-on: gradle:6.5.1-jdk11

    steps:
    - name: Fast Test
      run: gradle -i test

  slowTest:
    runs-on: gradle:6.5.1-jdk11

    steps:
    - name: Slow Test
      run: gradle -i slowTest

